server:
  port: 8080

solr:
  host: http://10.200.39.131:8602/solr/

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: config/logback.xml
  level:
    org.springframework.boot.devtools.restart.ChangeableUrls: OFF

job:
  cron-create: 0 * * * * *

address:
  baseUrl: https://vapi.vnappmob.com/api/province/

